### ISSUE TITLE
nodejs/node

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced-goals#39]

**Comment by bdougie** [comment]
could be a js file if typr module

mjs file

node already knows it is a module. 

```
file:///private/var/folders/7t/thbq5c7x72q06b5c4c7dj6xc0000gn/T/test/index.mjs:1
const data = require('./data.json')
             ^
ReferenceError: require is not defined
    at file:///private/var/folders/7t/thbq5c7x72q06b5c4c7dj6xc0000gn/T/test/index.mjs:1:14
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by bdougie** [comment]
wrap the await in a try/catch
